reactjs/react-router-redux

src/index.js
I was getting double ? before the query string in routing.path. I think this is because the location.query already has a ? in the front (and the same applies for hash). I removed the '?' that was being prepended which seems to fix the problem unless there are some edge cases I am missing.
=> Eliminate double ? from routing.path

src/index.js
I found a problem with Devtools where a 'RESET' will change the path to '/' regardless of the initial URL. This is the quick workaround I am currently using, but I wonder if there is a better way.
=> Restore location after devtools reset

package.json
When I tried using this library in a node 0.12.7 environment, my server side code failed due to Object.assign not being present.  Since the source is already being transpiled with es2016 presets, it seems to make sense to also replace Object.assign when not available.
=> Replace es2015 Object.assign for non es2015 environments

src/index.js
I have no idea if this is desirable or not, but figured I'd give it a shot just in case. I have a few projects with redux-router that are candidates for conversion to redux-simple-router, and it would be nice to be able to customize what the name of the property is on the store to maintain consistency.
If this is in fact something that might make sense but you can think of a more elegant implementation, I'm all ears. If not, I understand.
Thanks for a cool project.
=> Allow users to provide custom selectRouterState

src/index.js
I dispatch some actions to redux during the `history.listenBefore` hook, this causes multiple state changes before `window.location` is actually updated and before `history.listen` is fired. This causes an infinite loop, because `redux-simple-router` recognizes a route change at every state change, since `window.location` is still not updated, which in turn triggers the  `history.listenBefore` hook, which triggers new state changes, and so on. This PR fixes this issue by making sure not to re-invoke `pushState` unless the previous route transition is completed.
=> Prevent infinite loops when state is updated before the actual history change is fired

.gitignore, package.json, test/index.js
Add test coverage and some new tests to get up to near 100%
Statements   : 100% ( 34/34 )
Branches     : 95% ( 19/20 )
Functions    : 100% ( 9/9 )
Lines        : 100% ( 27/27 )
=> Increase test coverage

package.json, src/index.js, test/index.js
A couple of different changes here. Could split into multiple PRs, but wanted to see if you're interested first (I've also of course seen the PRs that already exist, but just copied this from the changes I needed for my app)
The changes:
- No longer use `window.location`, always rely on the `location` we receive from `history`
- Because of the above, let the initial state not be the current url, but set is with `noRouterUpdate=true`
- Add handling of `location.state` (and therefore a deep equal check when comparing locations)
- Use `history.createPath` instead of `locationToString`
- Make it possible to replace in addition to push
Also thought about renaming, but didn't for this PR:
- `updatePath` to `pushPath` (closer to `history.push` and `history.replace`)
- `noRouterUpdate` to …
=> Handle routing state and replace

README.md
I updated the README.md file so it use the `import`syntax from Ecmascript 6.
=> Update README.md to use import syntax from ES6.

src/index.js, test/index.js
I think we should be consistent about having `replace` correct in the store. It doesn't change much, but it _might_ be relevant if you play around with `UPDATE_PATH` in a reducer.
As far as I can tell `history` treats same url but different state as a replace:
```
history.pushState(null, '/foo');
// to
history.pushState({ bar: 'baz' }, '/foo');
```
I'm also open to just skip this one if we don't want the added "complexity".
=> Ensure correct push/replace state in store

src/index.js, test/index.js
PR for https://github.com/jlongster/redux-simple-router/issues/53.
This is a breaking change for folks who have a reducer for constant `UPDATE_PATH`. Bump version?
=> use FSA actions

examples/basic/app.js, examples/basic/components/App.js, examples/basic/package.json
This pull request add dev-tools to the basic example.
I hope this will help to fix #61.
=> Add Dev tools

test/createTests.js
I think this nicely cleaned up a couple of the tests. Plus it's easier to not specify the `changeId` while still keeping the tests easily readable.
=> Create test helper to improve tests

package.json, src/index.js, test/createTests.js
This is a WIP based on #70. With this change both devtools and the tests run (I didn't remove `changeId`, so might be there are something in the tests that actually isn't working as expected, of course). It solves the problems in https://github.com/jlongster/redux-simple-router/issues/61, as far as I can see.
Anyone else want to play around with it? Checkout this PR (help in https://help.github.com/articles/checking-out-pull-requests-locally/), copy in these changes, then run `npm run build` in root and then run `npm start` in `examples/basic/`, then open up `examples/basic/index.html` and test.
@jlongster Thoughts on https://github.com/kjbekkelund/redux-simple-router/commit/ef42b0fee67b048227b578652c69b4906492d389? Might be the change from `changeId` has broken something subtle. The …
=> Get devtools working

src/index.js
Had an issue in my app, in combination with `react-fetcher`, where `redux-simple-router` would create a history navigation on load, even though there's no reason to immediately navigate right on boot (the url is already in the URL bar).
Was this behavior intentional? Changing this line fixed the issue for me and I no longer have a redundant `UPDATE_PATH` on boot and an additional fetch.
If it helps, I'm pairing this with populating `state.routing.path` on the server side using `req.url`, so the routing path is correctly pre-populated on boot.
=> Don't navigate immediately on boot.

src/index.js
I added some info to the comments because I wanted to explain every detail as to how things work. I also change the code to remove early returns, as I think it is clearer.
Just opening a PR in case I made any mistakes, but I'd like to merge soon. All tests still pass.
=> update comments and avoid early returns

src/index.js
Here's my take on how we should solve some of our initialization issues:
1. Just change `initialState` to the current location on the first `history.listen` call (which is called immediately) (fixes devtools "revert")
2. Use the `lastRoute` as the flag to detect if it's the first `history.listen` call and also set it too (avoids making the store subscriber do another `pushState`, previously `lastRoute === undefined` was making it do that). (fixes code ike #81)
3. Create an `INIT_ACTION` so that people can still listen to `UPDATE_ACTION` *just* for changes. This is probably the most controversial. What should we do? Is it nice for `UPDATE_ACTION` to run through the reducers on page load or not? I would think it would not be.
=> Refactor initialization logic

CHANGELOG, README.md
Resolves #84 
:point_right: [Preview updated README](https://github.com/justingreenberg/redux-simple-router/tree/update-readme)
Clean up README and update syntax for #89
=> Update README and add CHANGELOG

.eslintrc, package.json, src/index.js, test/browser/index.js, test/createTests.js, test/node/index.js
There are no changes here except adding the [rackt eslint config](https://github.com/rackt/eslint-config-rackt) and fixing the errors. Related to #80
=> Add rackt eslint config

src/index.js, test/createTests.js
Closes #102 #103 
The problem with relying on `history.createPath` is that it might change in ways we don't want it to, e.g. as here when `history.createPath` prepends the basename, which means that the input to `pushPath` will differ from the path we create on a location change.
I think a good first step is to create the path ourselves (as we did in the previous version), and going forward to think about the ideas in #95 for later versions.
Thanks @dtryon and @hunterc for helping to fix this
=> Fix basename path issues

test/createTests.js
Tried to clean up the tests so they have less duplication and rely less on checking `changeId`, but focus more on checking what actually triggers `history.listen` (i.e. the external api for these changes). This should make it easier to tests changes to how we stop cycles.
I removed the test named "does not unnecessarily update the store", but added a "only triggers once when updating path via store" (which I created as part of #109, where I have a test which covers `history.pushState`).
=> Rely less on changeId in tests

src/index.js, test/browser/index.js, test/createTests.js, test/node/index.js
(I extracted the ES6 changes from #86, thanks @uniqname)
=> Change to ES6 imports and exports

src/index.js
No tests fail, so not sure we need this constant? We should either add a failing test or remove it.
The use case for removing this is receiving the initial URL when using `UPDATE_PATH`, e.g. #96.
(So the functional difference is: do we notify the initial route or only changes from the initial route?)
=> Remove `INIT_PATH`

.npmignore, package.json
This PR is to includes only necessary files in published tarball.
* Currently
```
-rw-r--r--  0 501    20       2082 12 21 15:58 package/package.json
-rw-r--r--  0 501    20        104 12 21 15:58 package/.npmignore
-rw-r--r--  0 501    20       7045 12 21 14:42 package/README.md
-rw-r--r--  0 501    20       1054 12 21 14:42 package/LICENSE
-rw-r--r--  0 501    20        120 12 21 14:42 package/tests.webpack.js
-rw-r--r--  0 501    20       1194 12 21 14:42 package/karma.conf.js
-rw-r--r--  0 501    20         27 12 21 14:42 package/.eslintrc
-rw-r--r--  0 501    20       1168 12 21 14:42 package/CHANGELOG.md
-rw-r--r--  0 501    20       5660 12 21 15:58 package/lib/index.js
-rw-r--r--  0 501    20      14775 12 21 14:42 package/test/createTests.js
-rw-r--r--  0 501    20        279 12 …
```
=> Add files fileds to package.json

src/index.js
Hi,
I was trying out the library and caught an error (due to a misunderstanding on my part).
```
Cannot sync router: route state does not exist. Did you install the routing reducer?
```
I thought I had installed the reducer in the right place, but erroneously placed it in `state.route` (and misinterpreted the error message to be leading me to `state.route`).
This PR adds a little bit more specificity to the error message.
No hard feelings if you think this might make error messages too wordy. Most of all, *thanks for making a routing library that is so simple I can actually debug my problems*!
=> Slight change to error message

examples/basic/package.json, package.json, src/index.js, test/createTests.js
original discussion #89 i tried to keep changes as minimal as possible since it sounds like there may be a rewrite happening soon
i can also submit a separate PR for devtools now that it's stable if you want
=> chore(history): update to history ^0.14.0 internally

.babelrc, package.json, src/index.js, test/createTests.js
Per https://github.com/rackt/redux-simple-router/pull/129#issuecomment-167392040.
Fixes https://github.com/rackt/redux-simple-router/issues/108.
The idea is basically - keep unidirectional data flow for updates, most of the time. This works in most cases, but it breaks replay, since the actions in some sense aren't pure. That's fine, though - we can restrict the store observer to _only_ handle the replay case (and potentially not even use it otherwise).
=> Use middleware to synchronize store to history

examples/basic/app.js
This branches off https://github.com/rackt/redux-simple-router/pull/141 to update the example app
=> updated example app to use middleware

src/index.js, test/createTests.js
You now get to them via the `routeActions` export.
```js
import { routeActions } from 'redux-simple-router'
routeActions.push('/foo')
```
This makes binding just the action creators in your `connect`s really easy:
```js
@connect(
someSelector,
dispatch => ({ router: bindActionCreators({ routeActions }, dispatch) })
)
class FooBar extends Component {
handleClick = () => {
this.props.router.push("/foo")
}
}
```
=> Export action creators in namespace. Add go, goBack, goForward

examples/basic/README.md, examples/basic/app.js, examples/basic/components/App.js, examples/basic/package.json, package.json, test/createTests.js
@jlongster here's a fresh PR for devtools, rebasing #137 was too painful... i can submit separate PR updating example to es modules and rackt style if you want, let me know :)
resolves #170
=> update (lib and example) to devtools stable

src/index.js
Correct way is to pass unknown actions to `next()` and `return` it's value.
Current implementation can break other middlewares
=> Do not swallow return value of next() in middleware

README.md
This PR updates the readme.md to reflect the API changes introduced mostly in https://github.com/rackt/redux-simple-router/pull/141 by @taion.
It also adds a little section for server-side usage - explaining that the memoryHistory has to be hydrated with the current location from the server for redux-simple-router to determine the correct initialState.
=> Prepare README for 2.0

src/index.js
This was wiping out state when not using `combineReducers` or reducing this reducer with others.
=> Include any previous state in routeReducer

examples/basic/app.js, src/index.js, test/createTests.js
@timdorr mentioned in https://github.com/rackt/redux-simple-router/issues/189#issuecomment-171524092 that this function is purely for devtools. I sort of forgot that it is completely for devtools, and because if this, I think we should rename the function. I propose `listenForReplays`, given that that's the usual use case. It might not be a replay that triggers it, but that's not a huge deal, it's something *like* a replay.
We can also mark this optional; people that don't use the devtools don't need it.
=> rename syncHistoryToStore to listenForReplays

README.md
Just fixed an issue in my app where I was using react-routers internal history and then another one via this tutorial.
=> Update docs to reflect internal history in react-router 2.0

src/index.js, test/createTests.js
Fix #206
Could use `redux-actions` to create the action creator, but that seems overkill
=> Make UPDATE_LOCATION follow FSA

examples/basic/package.json
Fixes fatal runtime error `Uncaught TypeError: middleware.listenForReplays is not a function`.
=> fix example by updating to 2.0.3

src/index.js
See https://github.com/rackt/redux-simple-router/pull/149#issuecomment-171802531 for rationale.
=> Also export unscoped action creators

README.md, src/index.js
This works for me with custom reducer:
```js
import { UPDATE_LOCATION } from 'redux-simple-router'
const initialState = new Immutable.Map({
location: undefined
})
export default function routeReducer(state = initialState, { type, payload: location }) {
if (type !== UPDATE_LOCATION) {
return state
}
return state.merge({ location })
}
```
and this `selectLocationState`
```js
const selectLocationState = function (state) {
const location = state.get('routing').get('location')
return location ? location.toJS() : location
}
```
=> Support ImmutableJS: use getLocationState instead of getRouterState as mentioned in #140

README.md
Add an example of getting route params from react-router in mapStateToProps.
=> Update README with info on react-redux route params

README.md, src/sync.js
=> Following feedback in #259

README.md, src/actions.js, src/index.js, src/middleware.js, test/actions.spec.js
Following comments on #259.
> I'm not sure keeping the old name is worth the confusion generated by introducing two actions.
>
>Especially now that we encourage calling history methods directly, people relying on the old action and thinking they don't need to change their analytics code will have broken code because direct history calls will not invoke the new action.
>
>I think CALL_HISTORY_METHOD might be the best choice here. It makes it clear this is not intended for analytics.
- @gaearon 
Also, let's not forget the the name already changed once in the past... 
> * `UPDATE_PATH` is now `UPDATE_LOCATION`.
=> rename UPDATE_LOCATION to CALL_HISTORY_METHOD

README.md
Includes a link to a commit migrating `^3.0.0` to `^4.0.0-beta`. Will update further once it's officially released.
=> Add example migration from ^3.0.0

README.md
Added another one example to new implementation
=> added example to readme

package.json, src/sync.js, test/_createSyncTest.js
We've been using the cutting edge version in a new project, and all work that went into v4 is much appreciated!
Today we found a bug: if the initial route redirects to another location, then the `Router` component doesn't update properly and leaves the user with an empty page. It's common to use `onEnter` on a `Route` to redirect the user to a login page when she is not logged. The `syncs history -> components when the initial route gets replaced` test in this PR replicates the problem.
The problem lies in the `syncHistoryWithStore`'s custom listening logic. It makes the first synchronous call to each listener before it subscribes to the store changes, so if the listener causes a location change and thus a store change (e.g. when a location redirects), then the listener is not notified of …
=> Fix issue when initial location redirects

README.md
Took me a while before I realized I needed to convert my Immutable object to a plain object for this to work, so this may help others
=> Update ImmutableJS instructions

README.md
This isn’t very clear right now, and causes some confusion.
=> Clarify the goal of this library

src/sync.js, test/_createSyncTest.js
This solves the problem when the server has initialised the state and the user already has things in their history.
Without this change a superfluous action will be pushed with the same URL that the user is already looking at resulting in that we would need to use the back button twice.
Resolves #313
=> Init currentLocation to initial location from the store

README.md
1. It was easier for me to think of the reducer by first knowing where
the state was expected to be. Writing it the other way around was
confusing
2. Add that the action payload data must go into the 
`locationBeforeTransitions` property
Closes #415
=> Improve instructions for using with Immutable.js

README.md
It's not used in 1st example, but used in the 2nd one.
This change makes it clear that following imports are coming from redux in the 2nd example, while cleaning up unused import in 1st.
=> README.md: move applyMiddleware to it's respective example

src/sync.js, test/_createSyncTest.js
This solves some problems where they would be out of sync on the first render when using server side rendering. The location would be the same for both of them but the `key` would be different resulting in some strange behaviour.
The application will now always dispatch a `LOCATION_CHANGE` on initial render. This was already done when not using server side rendering, meaning that the behaviour is similar between using server side rendering and not.
I have tested this manually and it seems to work fine. I have unfortunately not  enough time right now to add more tests.
I believe that this PR supersedes #412 and will probably address #444 and #429.
=> Makes sure the state in the store matches the state in history when using SSR

README.md
Broken links to reactjs/history get incorrectly forwarded to mjackson/history.  This fixes those links to point to the correct location
=> Broken links in README

README.md
I was going trough the README and found this broken link to `react-router` about `Getting URL Parameters`.
This PR should fix it.
Thank you for this awesome library 😸
=> Fix broken link to Getting URL Parameters
